### ISSUE TITLE
Error seen on travis run: Error: error:0306E06C:bignum routines:BN_mod_inverse:no inverse

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#390] opened 2016-02-14 03:41 UTC
I suppose this could be filed on fxa-jwtool, but anyways. /cc @dannycoates 

Can't duplicate it, and can't find the failing build log on travis now, since I restarted that build. 

It was with nodejs 4.3.0. Stack was:

```
fxa-oauth-server.summary.ERROR: summary {"code":500,"errno":999,"method":"post","path":"/v1/token",
 "agent":"shot","t":4,"client_id":"dcdb5ae7add825d2","auth":null,
 "payload":["client_id","client_secret","code","ttl","grant_type"],

"stack":"Error: error:0306E06C:bignum routines:BN_mod_inverse:no inverse\n    
at Error (native)\n    
at Sign.sign (crypto.js:279:26)\n    
at sign (/home/travis/build/jrgm/fxa-oauth-server/node_modules/fxa-jwtool/index.js:24:25)\n    
at PrivateJWK.signSync (/home/travis/build/jrgm/fxa-oauth-server/node_modules/fxa-jwtool/index.js:105:10)\n    
at PrivateJWK.sign (/home/travis/build/jrgm/fxa-oauth-server/node_modules/fxa-jwtool/index.js:119:25)\n    
at generateIdToken (/home/travis/build/jrgm/fxa-oauth-server/lib/routes/token.js:982:21)\n    
at generateTokens (/home/travis/build/jrgm/fxa-oauth-server/lib/routes/token.js:1001:20)\n    
at bound (domain.js:287:14)\n    
at runBound (domain.js:300:12)\n    
at tryCatcher (/home/travis/build/jrgm/fxa-oauth-server/node_modules/bluebird/js/main/util.js:26:23)\n    
at Promise._settlePromiseFromHandler (/home/travis/build/jrgm/fxa-oauth-server/node_modules/bluebird/js/main/promise.js:507:31)\n    
at Promise._settlePromise
At (/home/travis/build/jrgm/fxa-oauth-server/node_modules/bluebird/js/main/promise.js:581:18)\n    
at Promise._settlePromises (/home/travis/b
```

**Comment by shane-tomlinson** [comment] 2016-02-16 17:34
@dannycoates - can you triage this as you see appropriate?

**Comment by seanmonstar** [comment] 2016-02-16 18:18
This makes me think the key may be incorrect somehow. Is it directly in the config, or being loaded from the `keyFile` path?

**Comment by dannycoates** [comment] 2016-02-16 18:18
This looks like the the signing key was bad.

**Comment by rfk** [comment] 2016-02-16 23:52
We should check the key-generation script if we can detect bad keys up-front

**Comment by rfk** [comment] 2016-02-19 05:36
Here's one: https://travis-ci.org/mozilla/fxa-oauth-server/jobs/110306021

**Comment by rfk** [comment] 2016-02-19 05:56
Oh, it looks like our gen_keys script is using a pure-javascript node library to create its keys:

  https://www.npmjs.com/package/node-rsa

Possibly a bug in this library.  I'm able to reproduce it by doing "generate a key and try to sign something with it" in a tight loop.

**Comment by rfk** [comment] 2016-02-19 06:37
We already have generate-rsa-keypair in this repo for the tests, let's just switch to that which seems to work reliably.  I added a quick fix for this as part of https://github.com/mozilla/fxa-oauth-server/pull/392 because be damned if I'm going to use "restart test" on a PR that's specifically about fixing flaky tests.

**Comment by rfk** [comment] 2016-02-22 03:46
We fixed this in #392

**Closed by rfk** 2016-02-22 03:46 UTC
Labels: waffle:now

**Comment by vladikoff** [comment] 2016-02-22 16:19
It would be useful to let `node-rsa` know that something is not working correctly.

**Comment by rfk** [comment] 2016-02-22 20:38
It would, if we can figure out more about what was going on.  It wasn't obvious to me whether it was a problem in node-rsa or something funny in the way we were converting their keys into JWKs.  In my testing, node-rsa was able to sign data with keys that threw an error when we used them with jwtool.
