### ISSUE TITLE
2FA trust bootstrap issue (id_token vs user profile endpoint)

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/fxa-oauth-server#564] opened 2018-06-08 18:14 UTC
Imagine this flow:

- user has an FxA account without 2FA
- user logs in to discourse.mozilla.org with FxA
- user gets prompted to enable 2FA
- user enables 2FA for their FxA account
- user goes back to discourse.mozilla.org to login with FxA

At this point, the user has not been logged out of FxA, but has 2FA setup.

Mozilla IAM will see in the id_token that `acr` is `AAL1` because of this, though the user info endpoint (profile) will indicate that 2FA is setup. While this sounds technically correct, it's really a trust boostrap issue. If the user logs out and back in, you're none the wiser, except the id_token now reports `AAL2` - but it's not anymore safe then 2FA was just setup.

We have a work-around in place for this which checks both, but it also mean we lose the nice advantage of being able to say the session has really been authenticated with 2FA (for after-trust-boostrap scenarios).

A suggested change would be to change the session state in FxA so that the id_token reports `acr=AAL2` (and `amr` to include `totp` for example of course) as soon as the user *first* setup the new authentication factor.

**Comment by rfk** [comment] 2018-06-08 22:58
> user enables 2FA for their FxA account

I had thought that the act of enabling 2FA, would mark that session as 2FA-verified.  Are all of these steps done in the same browser login session?

**Comment by gdestuynder** [comment] 2018-06-08 23:01
yes

**Comment by vladikoff** [comment] 2018-06-18 15:55
from mtg: @rfk could you triage this?

**Comment by rfk** [comment] 2018-06-19 04:17
I nominated this for "next" and put it in the TOTP release milestone because AFAICT, this *should* work, so it may indicate a bug somewhere in our TOTP enablement procedure.  Next step is to produce some concrete steps to reproduce in a dev environment.

**Comment by rfk** [comment] 2018-06-27 22:46
> I had thought that the act of enabling 2FA, would mark that session as 2FA-verified.

I just tried this out, and it seems like the session is indeed marked as 2FA-verified when TOTP is enabled.  Signing a fresh certificate from the session gives me:

```
{ ..., "fxa-tokenVerified":true,"fxa-amr":["pwd","otp"],"fxa-aal":2,"iss":"api.accounts.firefox.com"}
```

So perhaps there's something else going on here, e.g. a caching issue which means we're using a certificate from before TOTP is enabled.

**Comment by rfk** [comment] 2018-06-27 22:58
@gdestuynder I was not able to reproduce this.  I tried the following:

* Visit https://discourse.mozilla.org/
* Click "sign up/log in", then click" Sign in with Firefox"
* Sign in with an existing test account that I have, without TOTP
* Get the error message instructing me to enable 2FA on my Firefox Account.
* Open the link to accounts.firefox.com in a new tab, enable TOTP, then close that tab
* Click the "go back" button on the error screen
* Click "Sign in with Firefox" again
* Re-enter my password in FxA to confirm that I want to login
* I was signed in successfully to discourse.mozilla.org

What steps differ for you when trying to repro this?

**Comment by rfk** [comment] 2018-06-27 23:04
> What steps differ for you when trying to repro this?

I thought maybe it would make a difference if I was signed in to sync, and thus got the "click to continue" experience rather than having to re-enter my password.  But it didnt, the flow still seemed to work correctly for me without having to sign out and back in to FxA.

I don't think we can investigate this any further without steps to reproduce.

**Comment by gdestuynder** [comment] 2018-06-28 22:45
> We have a work-around in place for this which checks both, but it also mean we lose the nice advantage of being able to say the session has really been authenticated with 2FA (for after-trust-boostrap scenarios).

This is why you cannot reproduce! : )

**Comment by gdestuynder** [comment] 2018-06-28 22:48
I turned the work-around off on https://social-ldap-pwless.testrp.security.allizom.org/

cc @viorelaioia  in case it causes test failures in dev

**Comment by rfk** [comment] 2018-06-28 23:12
> This is why you cannot reproduce!

Heh.  I was also checking some of the data going across the wire to see if it had the expected values in tokens, and it seemed to, but I could easily have missed the point where it disappears.  I'll find some time to try again in dev.

**Comment by rfk** [comment] 2018-07-02 05:58
> I turned the work-around off on https://social-ldap-pwless.testrp.security.allizom.org/

I tried the same steps from [above](https://github.com/mozilla/fxa-oauth-server/issues/564#issuecomment-400855620) at this URL and got the same result - enabling 2FA and then going back through the signin process again allowed me to login successfully.  So I'm still not able to reproduce this issue :-(

**Comment by rfk** [comment] 2018-07-18 22:49
> i'm guessing it has been fixed by requiring re-login for rps in some way?

If it has, that's an accidental side-effect.

I tried to reproduce this again, this time while signed in to sync in the browser.  I was able to access the RP without requiring a re-login, but things still went through successfully and appeared to have 2FA status correctly reported.

I don't think this bug is actionable on our side unless we can reproduce the unexpected behaviour.  I'm going to close it out, but please re-open if we can find concrete STR.

**Closed by rfk** 2018-07-18 22:49 UTC
Labels: waffle:next
